### PR TITLE
Updates to three display types: item detail, item browse, and search results

### PR DESCRIPTION
**Pull request by matt-bernhardt**
This is three tickets' worth of prototyping in one PR, so that we can compare them against each other.

### Why these changes are being introduced

There are three related display types in the Omeka theme, each of which needs to be updated to be ready to use the theme in production. The targeted displays are:

* Item pages
* Item browse (list of all items in a site)
* Search results

### How this addresses that need

This copies a few view templates from the Omeka application into the theme, allowing us to make some changes to them. Some of those changes are to bring them in line with coding standards, while the bulk of the changes were taken in conversation with stakeholders.

We also define a new set of SCSS modules that target these displays and their updated markup.

Along the way, we enable the resource settings UI that Omeka does not display unless certain conditions are met in the theme's `config.ini` file.

### Side effects of this change

The biggest side effect is probably making the theme a larger codebase (more templates, many more SCSS modules, etc).

I also worry whether we are repeating styles for `.resource` class in different contexts, but I haven't come up with a better way to approach this yet. The markup inside this class can differ between uses, but isn't entirely different. There's also a risk of going too far down an optimization rabbit hole without enough experience to judge the right amount.

Some other smaller points are mentioned in the commits on this branch - but they are relatively minor in nature.

### Relevant ticket(s)

* https://mitlibraries.atlassian.net/browse/post-87 (item page)
* https://mitlibraries.atlassian.net/browse/post-102 (search results)
* https://mitlibraries.atlassian.net/browse/post-113 (item browse)

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
I exported my local database and files, and attached them to https://mitlibraries.atlassian.net/browse/POST-87 . That ticket also includes some URLs within that content that will demonstrate the three displays that were developed in this PR.

**Review by jazairi — APPROVED** [review]
If I understand correctly (and I may well not), your concern has to do with making changes to the `.resource` class that are specific to div elements, while `.resource` may be used on other elements with the original Omeka CSS. I agree that it's not ideal, but this feels to me like the most direct way to make these changes.

**Comment by matt-bernhardt** [comment]
Yep - that's it exactly. I'm putting my faith, for the moment, in the fact that the project team is going to conduct usability and accessibility testing of this theme in the near future - and so there will be adjustments needed. The process of making those adjustments, after spending time away from these style rules, should give space to adjust the approach I'm taking here.

If that testing doesn't reveal that a change is needed, or the time away doesn't give perspective about an alternative approach, then that means that this should be fine. But if there's a better way, then future-me is more likely to see it than I am right now.

**Comment by jazairi** [comment]
Yeah, I think it's reasonable to assume that any issues caused by this approach would come up in QA.

On a somewhat related note, I was wondering this morning about a documentation strategy for this repo. Does it make sense to note in the readme what each of the module customizations do? I'm trying to think of what would be useful to a dev that has never worked with this repo but is tasked with changing something in the theme. Maybe that's a question we can't answer until that's actually happened, because I'm not quite sure yet what I'd need to know that isn't already in the readme.

Anyway, I don't have any specific recommendations for now, but it could be a good maintenance topic to consider down the road -- maybe even starting as a spike ticket.

**Pull request merged**
