### PR TITLE
Add configurable navigation menus

### PR DESCRIPTION
**Pull request by matt-bernhardt**
### Why these changes are being introduced

Omeka S has a very rudimentary implementation of a navigation menu, and it isn't really usable without a bit of work.

Additionally, by choosing to turn to a third-party library, we need a way to manage that dependency while also putting the library files in the expected locations (inside an asset/js folder, which is not a standard dependency location for many package managers)

### How this addresses that need

This PR has two principle steps:

1. Implements a way of managing a third-party JS library, using NPM and our Makefile. As a result of this step, we can use NPM to manage what version of SmartMenus we use (keeping up with future releases), while ultimately (after running `make update-js`) having that library in a location usable by Omeka.
2. Integrates that library with our theme, including a customizable choice of whether to use the menu as a navbar or a vertical menu alongside the content column.

### Side effects of this change

* If a site chooses to use the vertical navigation option, their site will appear wider to give everything the space it needs.
* For now, we are using the "Mint" style of the SmartMenus library; this will be updated in a future ticket when we implement the color variations feature in ticket [POST-65](https://mitlibraries.atlassian.net/browse/POST-65) later this sprint.

### Relevant ticket(s)

* https://mitlibraries.atlassian.net/browse/post-52

[POST-65]: https://mitlibraries.atlassian.net/browse/POST-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
Quick postscript, in case you looked at the changeset before I rebased on November 9th: I realized during rebasing that the navigation style overrides had been split across two files (one rule in base.scss, while the rest were in the navigation module file). As part of the rebase I consolidated all the overrides into the navigation module. Hopefully this makes the PR a bit easier to understand.

**Review by jazairi — APPROVED** [review]
I'd like to consider adding a note about this to the readme -- in particular, the "this CSS is copy/pasted, don't touch it" part. However, I think it may be a bit too soon to document since things appear to still be in flux.

**Comment by matt-bernhardt** [comment]
Good suggestion - I can add a commit to update the readme, describing what areas of the theme are imported from elsewhere. Even though the plan is to replace the mint theme with something more on-brand, there will still be _some_ parts of the SmartMenus library that will be imported.

Refactoring the deploy process as a whole may also be an option, but that's a Not Today issue.

**Review by jazairi — APPROVED** [review]
Looks good. Thanks for incorporating that suggestion.

**Pull request merged**
