### PR TITLE
Theme variants demonstration

### PR DESCRIPTION
**Pull request by matt-bernhardt**
### Why these changes are being introduced

We want to enable a bit of customization to sites on our platform, working within the branding guidelines laid out by Pentagram and the anticipated needs of the sites we create.

This is also a feature which Omeka themes have supported around the community (see [Union College](https://digitalcollections.union.edu/s/omeka-help/page/creating-a-website) for an example.

### How this addresses that need

This adds a field to the theme settings form, allowing site builders to choose from among a handful of color variants.

The impact of this setting can be seen from the following screenshots:

Screenshot 2023-12-21 at 1 18 37 PM
Screenshot 2023-12-21 at 1 18 49 PM
Screenshot 2023-12-21 at 1 19 00 PM
Screenshot 2023-12-21 at 1 19 13 PM
Screenshot 2023-12-21 at 1 19 24 PM
Screenshot 2023-12-21 at 1 19 33 PM

### Side effects of this change

None significant - a few CSS rules are adjusted in conjunction with the changes necessary to implement these colors. Details are in the first commit message.

### Relevant ticket(s)

https://mitlibraries.atlassian.net/browse/POST-65

### CODE REVIEW

**Comment by jazairi** [comment]
This all looks good to me, both in code and on the staging site. I'm seeing a couple errors in staging that I think are unrelated:

* The [welcome page](https://mitlibraries-stage.omeka.net/s/welcome) throws a 500
* A few of the sites listed in the ticket throw a 404:
    * Collecting Module Test
    * Landing page
    * Stephanie's test
    * Vail
    * Women @ MIT
 
I'm assuming the 404s are just related to permissions, and that none of these have anything to do with this changeset, but I wanted to make sure before I approve the PR.

**Comment by matt-bernhardt** [comment]
Thanks for asking. The easier point to address is the various sites in the ticket - those look like they're a case of not being published, so you would need to log in to see them (which makes sense, I think because those sites you listed aren't going to be ready initially - and in many cases are temporary experiments).

The welcome page throwing a 500 error is also related to not being signed in, but I'm not sure why the error is being thrown - it probably shouldn't be, but I struggle to construct a way for this PR to be causing the issue.

I'll look into that issue a bit and see whether I can unearth the actual cause.

**Comment by matt-bernhardt** [comment]
Ah, nevermind - that error was being thrown because the exhibit as a whole was published, but there was no published page within the exhibit - so Omeka was trying to forward the user to something they could see, and failing.

I've published the default page, and am no longer seeing that error message when I'm logged out.

**Comment by jazairi** [comment]
Got it. Thanks for looking into that!

**Review by jazairi — APPROVED** [review]

**Pull request merged**
